name: Train and Deploy Model
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  train-evaluate-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train the model
      run: python train.py

    - name: Check model accuracy
      id: check-accuracy
      run: |
        ACCURACY=$(python -c "import json; print(json.load(open('metrics.json'))['accuracy'])")
        echo "Model Accuracy: $ACCURACY"
        if (( $(echo "$ACCURACY >= 60" | bc -l) )); then
          echo "deploy=true" >> $GITHUB_OUTPUT
        else
          echo "deploy=false" >> $GITHUB_OUTPUT
          echo "Model accuracy is too low. Skipping deployment."
        fi

    - name: Clone Model Repository
      if: steps.check-accuracy.outputs.deploy == 'true'
      run: |
        git clone https://$HF_TOKEN@huggingface.co/danielle2003/diabetes-ml
        cd diabetes-ml
        git config --global user.email "danielledjofang2003@gmail.com"
        git config --global user.name "dani-ange"
      env:
        HF_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}

    - name: Deploy to Hugging Face
      if: steps.check-accuracy.outputs.deploy == 'true'
      run: |
        cd diabetes-ml
        cp ../diabetes_model.joblib .
        git add diabetes_model.joblib
        # Check if there are changes to commit
        if ! git diff --cached --quiet; then
          git commit -m "Updated model"
          git push
        else
          echo "No changes to deploy."
        fi
      env:
        HF_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
