name: Train and Deploy Model
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  train-evaluate-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Train the model
      run: python train.py

    - name: Check model accuracy
      id: check-accuracy
      run: |
        if [ ! -f metrics.json ]; then
          echo "metrics.json not found. Exiting..."
          exit 1
        fi
        ACCURACY=$(python -c "import json; print(json.load(open('metrics.json'))['accuracy'])")
        echo "Model Accuracy: $ACCURACY"
        python -c "import sys; sys.exit(0 if float('$ACCURACY') >= 60 else 1)"

    - name: Clone Model Repository
      run: |
        git clone https://$HF_TOKEN@huggingface.co/danielle2003/diabetes-ml diabetes-ml
        cd diabetes-ml
        git config user.email "danielledjofang2003@gmail.com"
        git config user.name "dani-ange"
      env:
        HF_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}

    - name: Deploy to Hugging Face
      run: |
        cd diabetes-ml
        cp ../diabetes_model.joblib .
        git add diabetes_model.joblib
        git commit -m "Updated model"
        git push
      env:
        HF_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}


