name: Train and Deploy Model
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  train-evaluate-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install huggingface_hub
      run: pip install huggingface_hub

    - name: Train the model
      run: python train.py

    - name: Check model accuracy
      id: check-accuracy
      run: |
        ACCURACY=$(python -c "import json; print(json.load(open('metrics.json'))['accuracy'])")
        echo "Model Accuracy: $ACCURACY"
        if (( $(echo "$ACCURACY < 60" | bc -l) )); then
          echo "Model accuracy is too low. Skipping deployment."
          exit 1
        fi

    - name: Authenticate with Hugging Face
      run: |
        python -c "from huggingface_hub import login; login('${{ secrets.HUGGINGFACE_API_TOKEN }}')"

    - name: Clone Model Repository using huggingface_hub
      run: |
        python -c "
        from huggingface_hub import HfApi;
        api = HfApi();
        api.repo_download(repo_id='danielle2003/diabetes-ml', local_dir='diabetes-ml')"

    - name: Deploy Model using huggingface_hub
      run: |
        python -c "
        from huggingface_hub import HfApi;
        import shutil;
        api = HfApi();
        shutil.copy('diabetes_model.joblib', 'diabetes-ml/diabetes_model.joblib');
        api.upload_file(
            path_or_fileobj='diabetes-ml/diabetes_model.joblib',
            path_in_repo='diabetes_model.joblib',
            repo_id='danielle2003/diabetes-ml',
            token='${{ secrets.HUGGINGFACE_API_TOKEN }}'
        )"
