name: Train and Deploy Model
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  train-evaluate-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Upgrade Hugging Face Hub
      run: pip install --upgrade huggingface_hub

    - name: Install Git LFS
      run: |
        sudo apt-get install git-lfs
        git lfs install

    - name: Authenticate with Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
      run: huggingface-cli login --token $HF_TOKEN --add-to-git-credential

    - name: Deploy to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
      run: |
        git config --global user.email "danielledjofang2003@gmail.com"
        git config --global user.name "dani-ange"
        
        # Ensure Git LFS tracks the right files
        git lfs track "*.joblib"
        git add .
        if ! git diff --cached --exit-code; then
            git commit -m "Updated model"
            git push https://danielle2003:$HF_TOKEN@huggingface.co/spaces/danielle2003/diabeties-ml main
        else
            echo "No changes to commit."
        fi
